### ISSUE TITLE
Get minified version of eruda.js for docs

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/webxdc_docs#2]
to link to in https://github.com/deltachat/webxdc_docs/blob/master/src/05_03b_debugging_with_eruda.md

**Comment by adbenitez** [comment]
I think this is not necessary, if eruda gets added as dependency and imported as module, then something like vite or webpack will minify it automatically :thinking: 

I edited the file and pointed to the eruda site in the meantime so at least reader can find eruda more easily

**Comment by Simon-Laux** [comment]
there is no direct download for the js file on the repo, just links to CDNs

**Comment by hpk42** [comment]
i don't think this level of detail is required -- we can at this point not provide a full handbook. 
I reviewed and refined eruda faq entry in #75 and fixed a link but close "minified eruda" because it's a detail and there is vite.  If you think anything is worthwhile here, please directly try to do a PR, thanks.
