### ISSUE TITLE
define app-id, version and description

### ISSUE THREAD

**Issue by adbenitez** [webxdc/webxdc_docs#58]
for the purpose of the app-store bot (and also in general in the long run) we need an app-id, version and description fields.

I am not sure about the naming we are using for the fields in the `manifest.toml` file, so it could be:
- `appid`
- `appId`
- `appID`
- `app_id`
- maybe just: `id`

`app-id`: should be an string, probably should be limited to some alphanumeric ASCII, `.` (dot), etc.

`version`: string or number? an string is useful for displaying to users ex. in the store, but a number is easier for comparison ex. to determine if version is older and shouldn't replace newer version, other option: call it `versionName` so it is a string label intended to be displayed to users (ex. in appstore), if not wanted right now, then introduce `version` field number when we run into troubles in the future wrt version comparison

`description`: just an string

**Comment by hpk42** [comment]
As discussed extensively in the chats, the current xdc store bot (for serving xdc apps to users)  does not require spec changes.  Once usage of the bot is real (say at least 5 extra developers submitted their apps) and people have used the xdcstore bot, we can reconsider if we want to add something to the spec.   Note that messenger implementations are not required to do anything about "app-id"/"version" so that's another reason to not target this spec change.

**Comment by ralphtheninja** [comment]
Just `id` is fine I think. Maybe use a guid format? And for version I'd pick the good old major/minor/patch format `x.y.z`

**Comment by hpk42** [comment]
For the current https://github.com/webxdc/store/ and https://codeberg.org/webxdc/xdcget efforts, addition to the spec are not needed.  There is a background "code signing" discussion as well as other considerations -- so far delta chat does not care at all about the fields discussed here, neither does Cheogram or Monocles.  Once we know why exactly we want to add new fields we can open another issue here. Closing this one here.
